# Generated by Django 4.2.7 on 2026-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safety", "0002_userlocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("crime", "Crime"),
                            ("scam", "Scam"),
                            ("weather", "Weather"),
                            ("crowd", "Crowd"),
                        ],
                        max_length=20,
                    ),
                ),
                ("risk_score", models.IntegerField()),
                ("description", models.TextField()),
                ("city", models.CharField(default="New Delhi", max_length=100)),
            ],
        ),
    ]
