# Generated by Django 4.2.7 on 2026-02-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safety", "0004_emergencyalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyalert",
            name="mode",
            field=models.CharField(
                choices=[("loud", "Loud"), ("silent", "Silent")],
                default="silent",
                max_length=10,
            ),
        ),
    ]
