# Generated by Django 4.2.7 on 2026-02-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safety", "0005_emergencyalert_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="CulturalGuide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(default="en", max_length=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("do", "Do"),
                            ("dont", "Dont"),
                            ("scam", "Scam"),
                            ("phrase", "Emergency Phrase"),
                        ],
                        default="do",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(default="", max_length=200)),
                ("content", models.TextField(default="")),
            ],
        ),
    ]
