# Generated by Django 4.2.7 on 2026-03-19 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("safety", "0009_crimerecord_workerprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncidentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("theft", "Theft"),
                            ("scam", "Scam"),
                            ("assault", "Assault"),
                            ("harassment", "Harassment"),
                            ("medical", "Medical"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("location_label", models.CharField(blank=True, default="", max_length=200)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("image_name", models.CharField(blank=True, default="", max_length=255)),
                ("risk_score_snapshot", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reported", "Reported"),
                            ("reviewing", "Reviewing"),
                            ("resolved", "Resolved"),
                        ],
                        default="reported",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incident_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
