# Generated by Django 4.2.16 on 2026-03-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0010_incidentreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="safepassageuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
