# Generated by Django 4.2.16 on 2026-03-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("safety", "0011_safepassageuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="blood_group",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="department",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="designation",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="emergency_contact_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="emergency_contact_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="home_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="usual_shift_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="usual_shift_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="work_location",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
