# Generated by Django 4.2.7 on 2026-03-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safety", "0012_workerprofile_extended_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checkin",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "I'm Safe"),
                    ("missed", "Missed"),
                    ("assistance", "Need Assistance"),
                    ("checkout", "Checked Out"),
                ],
                default="ok",
                max_length=20,
            ),
        ),
    ]
