# Generated by Django 4.2.7 on 2026-04-03 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("safety", "0014_workerprofile_leave_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="emergencyalert",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="acknowledged_by",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="token",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True
            ),
        ),
    ]
