# Generated by Django 4.2.7 on 2026-04-11 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safety", "0015_emergencyalert_acknowledged_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="emergency_contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
