# Generated by Django 4.2.7 on 2026-04-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safety", "0016_workerprofile_emergency_contact_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="company_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="company_phone",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="medications",
            field=models.TextField(blank=True, default=""),
        ),
    ]
