from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('predict/', views.risk_form, name='risk_form'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('dashboard/', views.tourist_dashboard_hub, name='tourist_dashboard_hub'),
    path('map/', views.tourist_risk_map, name='tourist_map_hub'),
    path('safe-route/', views.tourist_safe_route, name='tourist_safe_route'),
    path('cultural-safety/', views.tourist_cultural_guide, name='tourist_cultural_safety'),
    path('cultural-data/', views.get_cultural_data, name='cultural_data'),
    path('scam-alerts/', views.tourist_scam_alerts, name='tourist_scam_alerts'),
    path('emergency/', views.tourist_emergency_contacts, name='tourist_emergency_contacts'),
    path('sos/', views.tourist_emergency, name='tourist_sos'),
    path('alerts/', views.tourist_alerts, name='tourist_alerts'),
    path('translate/', views.tourist_translate, name='tourist_translate'),
    path('profile/', views.tourist_profile, name='tourist_profile_hub'),
    path('tourist/dashboard/', views.tourist_dashboard, name='tourist_dashboard'),
    path('tourist/risk-map/', views.tourist_risk_map, name='tourist_risk_map'),
    path('tourist/emergency/', views.tourist_emergency, name='tourist_emergency'),
    path('tourist/cultural-guide/', views.tourist_cultural_guide, name='cultural_guide'),
    path('tourist/profile/', views.tourist_profile, name='tourist_profile'),

    path('worker/dashboard/', views.worker_dashboard, name='worker_dashboard'),
    path('worker/shift/', views.worker_checkins, name='worker_shift_management'),
    path('worker/risk/', views.api_worker_risk, name='worker_risk'),
    path('worker/safe-route/', views.worker_route_planner, name='worker_safe_route'),
    path('worker/route-planner/', views.worker_route_planner, name='worker_route_planner'),
    path('worker/safe-havens/', views.worker_safe_havens, name='worker_safe_havens'),
    path('worker/check-in/', views.worker_checkins, name='worker_checkin'),
    path('worker/checkins/', views.worker_checkins, name='worker_checkins'),
    path('worker/map/', views.worker_risk_map, name='worker_map'),
    path('worker/sos/', views.worker_emergency, name='worker_sos'),
    path('worker/emergency/', views.worker_emergency, name='worker_emergency'),
    path('worker/alerts/', views.worker_alerts, name='worker_alerts'),
    path('worker/profile/', views.worker_profile, name='worker_profile'),

    # Worker API Endpoints
    path('api/worker/dashboard-data/', views.api_worker_dashboard_data, name='api_worker_dashboard_data'),
    path('api/worker/risk/', views.api_worker_risk, name='api_worker_risk'),
    path('api/worker/start-shift/', views.start_shift, name='start_shift'),
    path('api/worker/end-shift/', views.end_shift, name='end_shift'),
    path('api/worker/shift-status/', views.api_worker_shift_status, name='api_worker_shift_status'),
    path('api/worker/shift-preferences/', views.api_worker_shift_preferences, name='api_worker_shift_preferences'),
    path('api/worker/shift-escalation/', views.api_worker_shift_escalation, name='api_worker_shift_escalation'),
    path('api/worker/submit-checkin/', views.submit_checkin, name='submit_checkin'),
    path('api/worker/place-search/', views.api_worker_place_search, name='api_worker_place_search'),
    path('api/worker/safe-route/', views.get_safe_route, name='api_worker_safe_route'),
    path('api/worker/get-safe-route/', views.get_safe_route, name='get_safe_route'),
    path('api/worker/safe-havens/', views.api_worker_safe_havens, name='api_worker_safe_havens'),
    path('api/worker/alerts/', views.api_worker_alerts, name='api_worker_alerts'),
    path('api/worker/sos-target/', views.api_worker_sos_target, name='api_worker_sos_target'),
    path('employer/dashboard/', views.employer_dashboard, name='employer_dashboard'),
    
    # Admin Dashboard
    path('admin/dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/users/', views.admin_users, name='admin_users'),
    path('admin/risk-monitor/', views.admin_risk_monitor, name='admin_risk_monitor'),
    path('admin/sos-alerts/', views.admin_sos_alerts, name='admin_sos_alerts'),
    path('admin/incidents/', views.admin_incidents, name='admin_incidents'),
    path('admin/safe-zones/', views.admin_safe_zones, name='admin_safe_zones'),
    path('admin/analytics/', views.admin_analytics, name='admin_analytics'),
    path('admin/cultural-data/', views.admin_cultural_data, name='admin_cultural_data'),
    path('admin/notifications/', views.admin_notifications, name='admin_notifications'),
    path('admin/logs/', views.admin_system_logs, name='admin_system_logs'),
    path('admin/profile/', views.admin_profile, name='admin_profile'),
    path('api/admin/dashboard-data/', views.api_admin_dashboard_data, name='api_admin_dashboard_data'),
    path('api/admin/users/', views.api_admin_users, name='api_admin_users'),
    path('api/admin/risk-monitor/', views.api_admin_risk_monitor, name='api_admin_risk_monitor'),
    path('api/admin/sos-alerts/', views.api_admin_sos_alerts, name='api_admin_sos_alerts'),
    path('api/admin/incidents/', views.api_admin_incidents, name='api_admin_incidents'),
    path('api/admin/safe-zones/', views.api_admin_safe_zones, name='api_admin_safe_zones'),
    path('api/admin/analytics/', views.api_admin_analytics, name='api_admin_analytics'),
    path('api/admin/cultural-data/', views.api_admin_cultural_data, name='api_admin_cultural_data'),
    path('api/admin/notifications/', views.api_admin_notifications, name='api_admin_notifications'),
    path('api/admin/logs/', views.api_admin_logs, name='api_admin_logs'),
    path('api/admin/profile/', views.api_admin_profile, name='api_admin_profile'),
    
    path('privacy/', views.legal, name='privacy'),
    path('terms/', views.legal, name='terms'),
    path('contact/', views.contact, name='contact'),
    path('update-location/', views.update_location, name='update_location'),
    path('get-risk/', views.api_predict_risk, name='get_risk'),
    path('risk-score/', views.api_predict_risk, name='risk_score'),
    path('api/predict-risk/', views.api_predict_risk, name='api_predict_risk'),
    path('api/place-search/', views.api_place_search, name='api_place_search'),
    path('api/safe-route/', views.api_safe_route, name='api_safe_route'),
    path('api/incidents/', views.api_incidents, name='api_incidents'),
    path('api/alerts/', views.api_alerts, name='api_alerts'),
    path('api/weather-risk/', views.api_weather_risk, name='api_weather_risk'),
    path('api/cultural-advice/', views.api_cultural_advice, name='api_cultural_advice'),
    path('api/embassy-info/', views.api_embassy_info, name='api_embassy_info'),
    path('api/translate/', views.api_translate, name='api_translate'),
    path('api/report-incident/', views.api_report_incident, name='api_report_incident'),
    path('api/emergency/', views.api_emergency, name='api_emergency'),
    path('api/get-risk-zones/', views.get_risk_zones, name='get_risk_zones'),
    path('api/trigger-sos/', views.trigger_sos, name='trigger_sos'),
    path('api/get-cultural-data/', views.get_cultural_data, name='get_cultural_data'),
    path('api/sos-history/', views.api_sos_history, name='api_sos_history'),
    
    # Profile Management APIs
    path('api/save-profile/', views.save_profile, name='save_profile'),
    path('api/save-journey/', views.save_journey, name='save_journey'),
    path('api/add-contact/', views.add_contact, name='add_contact'),
    path('api/update-contact/<int:contact_id>/', views.update_contact, name='update_contact'),
    path('api/get-contact/<int:contact_id>/', views.get_contact, name='get_contact'),
    path('api/delete-contact/<int:contact_id>/', views.delete_contact, name='delete_contact'),
]
